### ISSUE TITLE
Update Modal component

### ISSUE THREAD

**Issue by tfoxley** [WCF-Insurance/WCF-Cashmere#136]
* Restyle to match our examples - see screenshot links below
* Fix margins as the modal responds to smaller screen widths
* Include some form elements in one example
* Include an example of a modal without buttons (has the X to dismiss in upper right)
* Add Usage tab and explain how to specify the size of the modal and what the options are (sm, md, lg, auto)

Here are some modal examples:
- Modal Alert: https://zpl.io/Vk7k518 | https://zpl.io/br0xNxX
- Modal Close: https://zpl.io/bPDlYBy | https://zpl.io/V1poqoX
- Modal Form: https://zpl.io/aXmQMjg | https://zpl.io/aMjMqMK

**Comment by c0d3r1010** [comment]
@tfoxley I am picking up this task today.
