### ISSUE TITLE
Create a Multi-Select form component

### ISSUE THREAD

**Issue by tfoxley** [WCF-Insurance/WCF-Cashmere#225]
- Allow filtering by typing in the text input
-- filter function will be passed in
- Allow multi-select
- Checked boxes bubble to the top of the list and groups them
- Once the options have been selected and Submit is clicked the selected results display below the input box (screenshot)
-- resolver function will be passed in to decide what text will be displayed for each selected item
- Make placeholder text in the input be configurable
-- When you click to submit, remove any text that has been typed in the input so that it goes back to the placeholder
- Make the number of items to display in the summary configurable
-- default to show all of them
-- if there are more results than the configured amount to show then just show the count as "12 selected items"
- Buttons will always be present
-- for first run it will always be Cancel and Submit
- Need to be able to re-hydrate selected options (for example, coming back to the page and reloading data)
- Add a required validation option that will require at least one option to be selected
- Hovering over an item should work the same as the Typeahead component
- No need to support single select

![image](https://user-images.githubusercontent.com/344920/88085532-36271600-cb43-11ea-9be8-decd2a964e83.png)

![screenshot-2](https://user-images.githubusercontent.com/344920/88086058-f9a7ea00-cb43-11ea-99fe-c3c69eacb24b.png)

**Comment by c0d3r1010** [comment]
Assuming a resolver function for configuration of placeholder
