### ISSUE TITLE
DateRange component needs to support a max duration

### ISSUE THREAD

**Issue by tfoxley** [WCF-Insurance/WCF-Cashmere#268]
We want to support a scenario where the end date will not be allowed to be greater than a specific period of time after the beginning date. This would need to be updated as the beginning date changes.

**Comment by c0d3r1010** [comment]
### Question 1: 

Assuming a max range of 7 days and that the date range picker is currently selected to that max range, what should happen if the user clicks a new start date that is a day before the existing start date?

### Question 2:

- Assuming any selected range equal to or less than the max range, what should happen if the user clicks a new start date that is after the current selected end date?

### Question 3a: 

Are we intending the begin date calendar to be able to select any date present or future but only allow the end date to select a date that would not be greater than the max period referenced from the start date? i.e. Is the start date sort of the driver and first step in selecting a range and the end date is sort of a sidecar that follows the driver around and can never select a date outside of the max range?

### Question 3b: 

Taking into account the context of **Question 3a** should there be a configurable min and max dates that neither the start nor end dates can go past? Sort of like outer bounds. I.e. If a period max of 7 days is configured you might want to still be able to configure that no dates greater than 3 months from now can be selected? This would be a max outer bound. On the other end maybe there is a minimum bound like no dates prior to the year 2020?

### Question X

I might have more questions depending on the answers. Also there are a number of quirks given the current logic built into the date range picker and sub components like the calendars etc...

**Comment by c0d3r1010** [comment]
1 ) show as invalid but don't slide the end date and don't clear it out.

2) same answer as # 1

3a) Yes the start date calendar is the driver and the end date calendar is like a side car that is subordinate to the start calendar.

3b) The min and max should for now only apply to the start calendar and not override anything or apply at all to the end calendar.  Also if the start date ever gets clear out then just disable all dates in the start calendar.
