### ISSUE TITLE
Make Navigating Through Years On Calendar More Intuitive

### ISSUE THREAD

**Issue by tfoxley** [WCF-Insurance/WCF-Cashmere#269]
Make our datepicker match the Angular Material Component (which is where it has roots) - https://material.angular.io/components/datepicker/overview

To navigate through the years, the user would need to click on the arrows next to the name of the month displayed: 
![image-2020-08-18-09-57-35-844](https://user-images.githubusercontent.com/344920/97193231-64ce1180-176e-11eb-934d-fffc89d92da5.png)

At first looking at this, it seemed like the only year selection available were for the past 6 years until it was told that the arrows next to the month displayed needed to be clicked on: 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/344920/97193253-6992c580-176e-11eb-9349-21315e348d08.png)

**Comment by c0d3r1010** [comment]
PR for this is almost ready to submit

**Comment by c0d3r1010** [comment]
PR: https://github.com/WCF-Insurance/WCF-Cashmere/pull/291
