### ISSUE TITLE
Date Picker: max date not working properly in the morning

### ISSUE THREAD

**Issue by tfoxley** [WCF-Insurance/WCF-Cashmere#289]
**Summary**

When you have a maxDate attribute set, in the morning, the max date is one day behind the date you set. Similar issue likely occurs with minDate in the evening.

**Reproduction**

When you have a maxDate attribute set in the morning, the max date is one day behind the date you set. The date picker only allows selection up to one day behind the date you pick as the max date.

![morning](https://user-images.githubusercontent.com/344920/102666143-78c93a80-4143-11eb-96e6-d6e966e47299.png)

In the afternoon, the date picker allows selection to the date you set as the max date (afternoon.png)

![afternoon](https://user-images.githubusercontent.com/344920/102666154-8088df00-4143-11eb-89e5-fa05185fd29c.png)

This can also be reproduced by changing your computers timezone if you don't want to test in the morning and then wait till the afternoon.

**Comment by c0d3r1010** [comment]
This is the date picker or the date range component? Looks like the date picker but wanted to confirm

**Comment by tfoxley** [comment]
Good catch @c0d3r1010 . I updated the title.

**Comment by c0d3r1010** [comment]
Look into if a similar solution is needed for the Date Range picker either non duration constricted or duration constricted.
