### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by wcf-mstacey** [WCF-Insurance/WCF-Cashmere#41]
A few of our apps are of the "wizard" style in which there is the need to display the progress through the wizard.

We want a re-usable component that we can interact with to track the overall progress of the app. The progress bar should be able to be interacted with, meaning a user can click on it to take them forward or backwards in the application.
If possible, it should be flexible enough to allow one app to allow the user to jump ahead (without completing interim pages), but in other apps require that they complete the page before continuing.

![image](https://user-images.githubusercontent.com/45216558/56767961-3f6fda00-676a-11e9-99b3-98a218342bb2.png)

**Comment by c0d3r1010** [comment]
@wcf-mstacey Here is proposed AC to ensure we have all the details written:

Acceptance Criteria:

- Should display user's progress as they step through the wizard
- Progress bar items should have three possible states:
-- Completed step
-- Currently visible (but not completed) step
-- Uncompleted step
- User should be able to navigate forward or backward by clicking the desired wizard section
- Should be configurable to allow dev to toggle two scenarios:
-- Allow user to jump ahead without completing interim pages
-- Prevent user from jumping ahead

Technical Considerations
- Should allow for external configuration to set initial state of progress items or to update all items later on in the user flow. Potential for api to allow for an input property to indicate a change on a specific progress item but at the moment it seems like having the consuming component simply pass all state for each change may be best.

**Comment by c0d3r1010** [comment]
Additional Scope or Items from our demo meeting on 7/9:
- [ ] Update to use the thermostat styling on current selected item and all previous items. This changes the current behavior which was to show thermostat styling based on latest completed item and all items previous to latest completed.
- [ ] Always square off the last step / progress item regardless of if it is completed or not. This will be seen when selecting the last item.
- [ ] Completed items should no longer be red with white check mark unless that item is the current selected item. When a completed item is not currently selected then it should show a red check mark on a white background
- [ ] Pointer should only show on progress items that are selectable. An item is currently selectable if skip ahead is turned on or if the item is the next item after a completed item.
