### ISSUE TITLE
Issues with the :focus state of some elements.

### ISSUE THREAD

**Issue by tommybay** [WCF-Insurance/WCF-Cashmere#72]
**Describe the bug**
The input components that we're bringing into our project do not have a visible :focus style applied. If I click into an input field or if I a tab through a form, I don't get a focus outline or glow or anything. This is particularly problematic if there are radio / checkbox sets because I don't know when that set of inputs is being focused and, therefore, don't know that I can arrow through the options.

**To Reproduce**
1.  Go to the Form Field component
2. Tab through the form

**Expected behavior**
Some of the elements / inputs will not indicate that they are in a focused state. Specifically, the only elements that DO show a focus state on this page are the dropdown and the button.

**Additional context**
We talked about this in Slack. :)

**Comment by c0d3r1010** [comment]
@tommybay, @tfoxley and @wcf-mstacey 

I think I have this working the way it needs to but I need to validate what style is intended. Currently I set this to use the same focus style as chrome provides for the hc-select and the hc-button.

Here are some screenshots (textbox not yet done):

![#71_radio_btn_focus](https://user-images.githubusercontent.com/43886631/63664457-d1710900-c783-11e9-9278-ebe4514a6809.PNG)

![#71_existing_select_box_focus](https://user-images.githubusercontent.com/43886631/63664608-8a374800-c784-11e9-99b6-bc1c397ea15a.PNG)


![#71_checkbox_btn_focus](https://user-images.githubusercontent.com/43886631/63664466-d930ad80-c783-11e9-8217-7df3f2ec423d.PNG)

![#71_existing_button_focus](https://user-images.githubusercontent.com/43886631/63664613-928f8300-c784-11e9-922c-a2ca533bc9fc.PNG)

**Comment by c0d3r1010** [comment]
Since there was a code freeze I took the liberty to add the dramatized styles.

**Comment by c0d3r1010** [comment]
Also I improved the blue glow a little since the screenshots I shared in Slack on Friday (9/6). Looks awesome!

**Comment by c0d3r1010** [comment]
@tommybay Should we close this issue?
