### ISSUE TITLE
Make the Sidenav component responsive

### ISSUE THREAD

**Issue by tommybay** [WCF-Insurance/WCF-Cashmere#91]
**Describe the problem this feature request is solving**
Currently, any time the Sidenav component is used in an app, it blocks 90% of the screen width on a smart phone.

**Describe the solution you'd like**
We'd like to have the sidenav collapse into a hidden drawer that slides out when tapping a hamburger icon in the app header.

** If any, which components will have to change, and how **
I'm not completely sure, but I believe the Sidenav component will need to change in the following ways:
- Needs to be built inside a drawer
- The drawer needs to either be set to always be open above 768px screen width, and hidden below 768px OR we could set a parameter that could be passed in that determines which breakpoint at which to hide the sidenav/drawer
- If the drawer is hidden, show a hamburger icon button
- If the hamburger icon is tapped, reveal the drawer and change the hamburger icon to a close icon
- If the close icon is tapped, or if you tap (click) outside of the drawer, the drawer should hide and the icon should change back to the hamburger

**Additional context**
I'd be very surprised if this write-up covers everything. Please ask if you have questions!
Here's a link to the design concept in Zeplin: https://zpl.io/2pPxrNl

**Comment by c0d3r1010** [comment]
I will start on this tonight or tomorrow, thanks Tommy!

**Comment by c0d3r1010** [comment]
@tommybay Would you be able to provide a screenshot of the existing behavior for the sidenav that you see on mobile and desktop? I am planning out the work for this and want to better understand the current scenario. Thanks!

**Comment by tommybay** [comment]
@c0d3r1010 
I'll slack you a video of the current behavior.

**Comment by c0d3r1010** [comment]
Per demo conversation the criteria will also include main content scolling, sticky sidenav (currently the case), and the links inside the sidenav can be scolled if too much content.

**Comment by tfoxley** [comment]
Looks good. Nice work. Closing the issue.
